Switch to ssize_t

diff --git a/src/lib/libast/features/common b/src/lib/libast/features/common
--- a/src/lib/libast/features/common
+++ b/src/lib/libast/features/common
@@ -274,7 +274,7 @@ tst	- output{
 	exit 1
 }end
 
-tst note{ generating _ast_flt\*_t and signed_size_t types }end output{
+tst note{ generating _ast_flt\*_t types }end output{
 	#define _BYTESEX_H
 
 	#include <unistd.h>
@@ -321,27 +321,10 @@ tst note{ generating _ast_flt\*_t and signed_size_t types }end output{
 		printf("#define _ast_fltmax_t		_ast_flt%d_t\n", m);
 		if (m == sizeof(double))
 			printf("#define _ast_fltmax_double		1\n");
-		/*
-		 * Create a typedef for a signed_size_t type (because ssize_t and ptrdiff_t
-		 * are not always the same).
-		 */
-		if (sizeof(int) == sizeof(size_t))
-			printf("typedef int	signed_size_t;\n");
-	#if __STDC_VERSION__ >= 199901L
-		else if (sizeof(long long) == sizeof(size_t))
-			printf("typedef long long	signed_size_t;\n");
-	#endif
-		else if (sizeof(long) == sizeof(size_t))
-			printf("typedef long	signed_size_t;\n");
-		else
-		{
-			NOTE("Could not generate signed_size_t!");
-			return 1;
-		}
 		return 0;
 	}
 }end fail{
-	echo "$0: Could not generate _ast_flt*_t or signed_size_t types. Export IFFEFLAGS=-d1 to debug." >&2
+	echo "$0: Could not generate _ast_flt*_t types. Export IFFEFLAGS=-d1 to debug." >&2
 	exit 1
 }end
 
